# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
# Do similar for other three images

# Tagging
  - docker tag udagram-api-feed trunglam12/udagram-api-feed:v1
# Do similar for other three images```
```bash
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trunglam12/udagram-api-feed:v1
# Do similar for other three images