apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: trunglam12/udagram-api-user:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: username
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: jwt-secret
          envFrom:
            - configMapRef:
                name: env-configmap
